auxiliar=input()
codigo1, numero1, valor1=auxiliar.split()
codigo1 = float(codigo1)
numero1 = float(numero1)
valor1 = float(valor1)
auxiliar2=input()
codigo2, numero2, valor2=auxiliar2.split()
codigo2 = float(codigo2)
numero2 = float(numero2)
valor2 = float(valor2)
total= (numero1 * valor1) + (numero2 * valor2)
print(f"VALOR A PAGAR: R$ {total:.2f}")
